/*
 * generated by Xtext
 */
package at.bestsolution.efxclipse.tooling.decora.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DecoraDslUiModule extends at.bestsolution.efxclipse.tooling.decora.ui.AbstractDecoraDslUiModule {
	public DecoraDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
