/*
* generated by Xtext
*/
package at.bestsolution.efxclipse.tooling.decora.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DecoraDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("at/bestsolution/efxclipse/tooling/decora/parser/antlr/internal/InternalDecoraDsl.tokens");
	}
}
