/*
* generated by Xtext
*/
package at.bestsolution.efxclipse.tooling.decora.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.bestsolution.efxclipse.tooling.decora.services.DecoraDslGrammarAccess;

public class DecoraDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DecoraDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_COMMENT", "RULE_LINE_COMMENT", "RULE_WS");
	}
	
	@Override
	protected at.bestsolution.efxclipse.tooling.decora.parser.antlr.internal.InternalDecoraDslParser createParser(XtextTokenStream stream) {
		return new at.bestsolution.efxclipse.tooling.decora.parser.antlr.internal.InternalDecoraDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public DecoraDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DecoraDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
