/*
 * generated by Xtext
 */
package at.bestsolution.efxclipse.tooling.efxbean;

import org.eclipse.xtext.generator.IGenerator;

import at.bestsolution.efxclipse.tooling.efxbean.generator.FXBeanGenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FXBeanRuntimeModule extends at.bestsolution.efxclipse.tooling.efxbean.AbstractFXBeanRuntimeModule {
	/* (non-Javadoc)
	 * @see at.bestsolution.efxclipse.tooling.efxbean.AbstractFXBeanRuntimeModule#bindIGenerator()
	 */
	@Override
	public Class<? extends IGenerator> bindIGenerator() {
		return FXBeanGenerator.class;
	}
}
