/*
 * generated by Xtext
 */
package at.bestsolution.efxclipse.tooling.decora;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DecoraDslRuntimeModule extends at.bestsolution.efxclipse.tooling.decora.AbstractDecoraDslRuntimeModule {

}
