/*
* generated by Xtext
*/
package at.bestsolution.efxclipse.tooling.efxbean.ui.contentassist;

import at.bestsolution.efxclipse.tooling.efxbean.ui.contentassist.AbstractFXBeanProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class FXBeanProposalProvider extends AbstractFXBeanProposalProvider {

}
