/*
 * generated by Xtext
 */
package at.bestsolution.efxclipse.tooling.rrobot.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RTaskUiModule extends at.bestsolution.efxclipse.tooling.rrobot.dsl.ui.AbstractRTaskUiModule {
	public RTaskUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
