/*
* generated by Xtext
*/
package at.bestsolution.efxclipse.tooling.decora.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class DecoraDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
