/*
* generated by Xtext
*/
package at.bestsolution.efxclipse.tooling.decora;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DecoraDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return at.bestsolution.efxclipse.tooling.decora.ui.internal.DecoraDslActivator.getInstance().getInjector("at.bestsolution.efxclipse.tooling.decora.DecoraDsl");
	}
	
}
