/*
* generated by Xtext
*/
package at.bestsolution.efxclipse.tooling.decora.ui.contentassist;

import at.bestsolution.efxclipse.tooling.decora.ui.contentassist.AbstractDecoraDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DecoraDslProposalProvider extends AbstractDecoraDslProposalProvider {

}
