/*
* generated by Xtext
*/
package at.bestsolution.efxclipse.tooling.rrobot.dsl.ui.contentassist;

import at.bestsolution.efxclipse.tooling.rrobot.dsl.ui.contentassist.AbstractRTaskProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class RTaskProposalProvider extends AbstractRTaskProposalProvider {

}
