/*
* generated by Xtext
*/
package at.bestsolution.efxclipse.tooling.rrobot.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.bestsolution.efxclipse.tooling.rrobot.dsl.services.RTaskGrammarAccess;

public class RTaskParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RTaskGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.bestsolution.efxclipse.tooling.rrobot.dsl.parser.antlr.internal.InternalRTaskParser createParser(XtextTokenStream stream) {
		return new at.bestsolution.efxclipse.tooling.rrobot.dsl.parser.antlr.internal.InternalRTaskParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "RobotTask";
	}
	
	public RTaskGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RTaskGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
