/*
 * generated by Xtext
 */
package at.bestsolution.efxclipse.tooling.css.cssext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

import at.bestsolution.efxclipse.tooling.css.cssext.ui.highlighting.CssExtHighlightingConfiguration;
import at.bestsolution.efxclipse.tooling.css.cssext.ui.highlighting.CssExtSemanticHighlightingCalculator;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CssExtDslUiModule extends at.bestsolution.efxclipse.tooling.css.cssext.ui.AbstractCssExtDslUiModule {
	public CssExtDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public void configure(Binder binder) {
		
		binder.bind(ISemanticHighlightingCalculator.class).to(CssExtSemanticHighlightingCalculator.class);
		binder.bind(IHighlightingConfiguration.class).to(CssExtHighlightingConfiguration.class);
		
		binder.bind(ICssExtManager.class).toInstance(new CssExtManager());
		
		super.configure(binder);
	}
}
