/*
* generated by Xtext
*/
package at.bestsolution.efxclipse.tooling.efxbean;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class FXBeanUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return at.bestsolution.efxclipse.tooling.efxbean.ui.internal.FXBeanActivator.getInstance().getInjector("at.bestsolution.efxclipse.tooling.efxbean.FXBean");
	}
	
}
