/*
* generated by Xtext
*/
package at.bestsolution.efxclipse.tooling.efxbean.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.bestsolution.efxclipse.tooling.efxbean.services.FXBeanGrammarAccess;

public class FXBeanParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FXBeanGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.bestsolution.efxclipse.tooling.efxbean.parser.antlr.internal.InternalFXBeanParser createParser(XtextTokenStream stream) {
		return new at.bestsolution.efxclipse.tooling.efxbean.parser.antlr.internal.InternalFXBeanParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "FXBeanUnit";
	}
	
	public FXBeanGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FXBeanGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
