/*
* generated by Xtext
*/
package at.bestsolution.efxclipse.tooling.css.cssext.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import at.bestsolution.efxclipse.tooling.css.cssext.cssExtDsl.CSSRule;
import at.bestsolution.efxclipse.tooling.css.cssext.cssExtDsl.CSSRuleDefinition;
import at.bestsolution.efxclipse.tooling.css.cssext.cssExtDsl.CSSRuleRef;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class CssExtDslLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public CssExtDslLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	
	String text(CSSRuleDefinition model) {
		return model.getName().getName() + " =";
	}
	
	String text(CSSRuleRef ruleRef) {
		return "&lt;" + ruleRef.getRef().getName() + "&gt;";
	}
	
/*
	//Labels and icons can be computed like this:
	
	String text(MyModel ele) {
	  return "my "+ele.getName();
	}
	 
    String image(MyModel ele) {
      return "MyModel.gif";
    }
*/
}
