/*
 * generated by Xtext
 */
package at.bestsolution.efxclipse.tooling.efxbean.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FXBeanUiModule extends at.bestsolution.efxclipse.tooling.efxbean.ui.AbstractFXBeanUiModule {
	public FXBeanUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
